#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

const IGNORED_FILES = ['_app', '_document', '_error', 'layout', 'loading', 'error', 'not-found', 'template', 'head', 'api'];
const EXTENSIONS = ['.js', '.jsx', '.ts', '.tsx'];

function scanDirectory(dir: string, basePath = ''): string[] {
    let routes: string[] = [];

    if (!fs.existsSync(dir)) return routes;

    const files = fs.readdirSync(dir);

    for (const file of files) {
        const fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            // Skip api directory
            if (file === 'api') continue;

            // Handle route groups (e.g., (marketing))
            const segment = file.startsWith('(') && file.endsWith(')') ? '' : file;
            const newBasePath = path.join(basePath, segment).replace(/\\/g, '/');

            routes = routes.concat(scanDirectory(fullPath, newBasePath));
        } else {
            const ext = path.extname(file);
            if (!EXTENSIONS.includes(ext)) continue;

            const name = path.basename(file, ext);

            // Filter ignored files
            if (IGNORED_FILES.includes(name)) continue;
            if (name.startsWith('_')) continue; // _app, _document

            let routePath = basePath;

            if (name !== 'index' && name !== 'page') {
                routePath = path.join(basePath, name).replace(/\\/g, '/');
            }

            // Ensure leading slash
            if (!routePath.startsWith('/')) {
                routePath = '/' + routePath;
            }

            // Fix Windows paths just in case
            routePath = routePath.replace(/\\/g, '/');

            // Skip dynamic routes for now as they are hard to fuzzy match against static strings
            // e.g., /products/[id]
            if (routePath.includes('[')) continue;

            routes.push(routePath);
        }
    }

    return routes;
}

function generateRoutes() {
    const cwd = process.cwd();
    const pagesDir = path.join(cwd, 'pages');
    const appDir = path.join(cwd, 'app');
    const srcPagesDir = path.join(cwd, 'src', 'pages');
    const srcAppDir = path.join(cwd, 'src', 'app');

    let routes: string[] = [];

    if (fs.existsSync(pagesDir)) {
        console.log('Scanning pages/ directory...');
        routes = routes.concat(scanDirectory(pagesDir));
    } else if (fs.existsSync(srcPagesDir)) {
        console.log('Scanning src/pages/ directory...');
        routes = routes.concat(scanDirectory(srcPagesDir));
    }

    if (fs.existsSync(appDir)) {
        console.log('Scanning app/ directory...');
        routes = routes.concat(scanDirectory(appDir));
    } else if (fs.existsSync(srcAppDir)) {
        console.log('Scanning src/app/ directory...');
        routes = routes.concat(scanDirectory(srcAppDir));
    }

    // Deduplicate
    routes = Array.from(new Set(routes));

    const content = `// Auto-generated by fuzzy-redirect
export const fuzzyRoutes = ${JSON.stringify(routes, null, 2)};
`;

    const outputPath = path.join(cwd, 'fuzzy-routes.ts');
    fs.writeFileSync(outputPath, content);

    console.log(`✅ Generated ${routes.length} routes to fuzzy-routes.ts`);
}

generateRoutes();
